
#### Data

This data includes over 3,100 ratings on different types of ramen around the world. The dataset contains 6 variables, including 2 numeric variables:

- review_number: Ramen review number

- stars: Rating of the ramen, 5 is best, 0 is worst

and 4 categorical variables:

- brand: Brand of the ramen

- variety: The ramen variety, e.g., a flavor, style, ingredient

- style: Style of container (cup, pack, tray)

- country: Origin country of the ramen brand

The data is collected from the [Ramen Rater](https://www.theramenrater.com/resources-2/the-list/). 


#### Purpose

The purpose of the app is to:

1. show an overview of how ramen varieties are distributed across selected countries,
2. show what are the highest rated ramen brands and how different ramen styles can affect raters' preference towards particular brands, and 
3. allow users to freely explore in details and understand about different ramen brands, including the reviews, country of origin, etc. 

The first part indicates that  majority of ramen distribution are located in Asian countries, namely South Korea, Japan, Indonesia and Thailand. The second part provided a feature to let users learn more about the origin of various ramen varieties and how they are rated based on reviewers around the wold. From the last part, it can be seen that the most poular ramen styles that are highly preferred are bowl and pack. The app also utilized interactive components to show the changes in ramen ratings in response to different locations and different styles (e.g. world map and interactive graphs).

#### Creator

Phuong Thanh Trinh (ptri0004@student.monash.edu)

<details>
<summary>Session information</summary>
```{r, echo = FALSE}
sessioninfo::session_info()
```
</details>
